name: Python compiler linux

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: python version
      run: python --version
    - name: pyinstaller version
      run: pyinstaller --version
    
    

    - name: Setup C++ environment
      uses: kurocha/setup-cpp@v1
      
    - name: compile C library "blast"
      run: gcc -o ./src/lib/blast_args ./src/lib/blast_args.c
    
    - name: run SSAtool directly
      run: python ./src/SSAtool.py -v
    
    - name: compile SSAtool
      run: pyinstaller -F --add-data "./src/lib/blast_args:." ./src/SSAtool.py
      
    - name: run compiled version
      run: ./dist/SSAtool -v

    - name: save compiled SSAtool
      uses: actions/upload-artifact@master
      with:
        name: SSAtool_linux
        path: ./dist/SSAtool
